// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  TypedMap,
  Entity,
  Value,
  ValueKind,
  store,
  Address,
  Bytes,
  BigInt,
  BigDecimal,
} from "@graphprotocol/graph-ts";

export * from "./schemas/staticJobs";
export * from "./schemas/gasVault";
export * from "./schemas/whitelist";
export * from "./schemas/leaderBoard";

export class Keeper extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("bondHeld", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("index", Value.fromBigInt(BigInt.zero()));
    this.set("status", Value.fromString(""));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Keeper entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Keeper entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Keeper", id.toString(), this);
    }
  }

  static load(id: string): Keeper | null {
    return changetype<Keeper | null>(store.get("Keeper", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get bondHeld(): BigDecimal {
    let value = this.get("bondHeld");
    return value!.toBigDecimal();
  }

  set bondHeld(value: BigDecimal) {
    this.set("bondHeld", Value.fromBigDecimal(value));
  }

  get index(): BigInt {
    let value = this.get("index");
    return value!.toBigInt();
  }

  set index(value: BigInt) {
    this.set("index", Value.fromBigInt(value));
  }

  get actions(): Array<string> {
    let value = this.get("actions");
    return value!.toStringArray();
  }

  set actions(value: Array<string>) {
    this.set("actions", Value.fromStringArray(value));
  }

  get status(): string {
    let value = this.get("status");
    return value!.toString();
  }

  set status(value: string) {
    this.set("status", Value.fromString(value));
  }

  get queueTimeline(): Array<string> {
    let value = this.get("queueTimeline");
    return value!.toStringArray();
  }

  set queueTimeline(value: Array<string>) {
    this.set("queueTimeline", Value.fromStringArray(value));
  }

  get permissionUpdates(): Array<string> {
    let value = this.get("permissionUpdates");
    return value!.toStringArray();
  }

  set permissionUpdates(value: Array<string>) {
    this.set("permissionUpdates", Value.fromStringArray(value));
  }
}

export class Runner extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("bondHeld", Value.fromBigInt(BigInt.zero()));
    this.set("createdAt", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Runner entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Runner entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Runner", id.toString(), this);
    }
  }

  static load(id: string): Runner | null {
    return changetype<Runner | null>(store.get("Runner", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get bondHeld(): BigInt {
    let value = this.get("bondHeld");
    return value!.toBigInt();
  }

  set bondHeld(value: BigInt) {
    this.set("bondHeld", Value.fromBigInt(value));
  }

  get createdAt(): BigInt {
    let value = this.get("createdAt");
    return value!.toBigInt();
  }

  set createdAt(value: BigInt) {
    this.set("createdAt", Value.fromBigInt(value));
  }
}

export class QueueTimeline extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("keeper", Value.fromString(""));
    this.set("timeDelay", Value.fromBigInt(BigInt.zero()));
    this.set("queued", Value.fromBoolean(false));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save QueueTimeline entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save QueueTimeline entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("QueueTimeline", id.toString(), this);
    }
  }

  static load(id: string): QueueTimeline | null {
    return changetype<QueueTimeline | null>(store.get("QueueTimeline", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get keeper(): string {
    let value = this.get("keeper");
    return value!.toString();
  }

  set keeper(value: string) {
    this.set("keeper", Value.fromString(value));
  }

  get timeDelay(): BigInt {
    let value = this.get("timeDelay");
    return value!.toBigInt();
  }

  set timeDelay(value: BigInt) {
    this.set("timeDelay", Value.fromBigInt(value));
  }

  get queued(): boolean {
    let value = this.get("queued");
    return value!.toBoolean();
  }

  set queued(value: boolean) {
    this.set("queued", Value.fromBoolean(value));
  }
}

export class PermissionUpdate extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("keeper", Value.fromString(""));
    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
    this.set("action", Value.fromString(""));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save PermissionUpdate entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save PermissionUpdate entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("PermissionUpdate", id.toString(), this);
    }
  }

  static load(id: string): PermissionUpdate | null {
    return changetype<PermissionUpdate | null>(
      store.get("PermissionUpdate", id)
    );
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get keeper(): string {
    let value = this.get("keeper");
    return value!.toString();
  }

  set keeper(value: string) {
    this.set("keeper", Value.fromString(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }

  get action(): string {
    let value = this.get("action");
    return value!.toString();
  }

  set action(value: string) {
    this.set("action", Value.fromString(value));
  }
}

export class OrchestratorAction extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("timestamp", Value.fromBigInt(BigInt.zero()));
    this.set("from", Value.fromString(""));
    this.set("state", Value.fromString(""));
    this.set("status", Value.fromString(""));
    this.set("recipients", Value.fromStringArray([]));
    this.set("hash", Value.fromString(""));
    this.set('transactionHash', Value.fromString(''));
    this.set('vault', Value.fromString(''));
    this.set('gasUsed', Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save OrchestratorAction entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save OrchestratorAction entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("OrchestratorAction", id.toString(), this);
    }
  }

  static load(id: string): OrchestratorAction | null {
    return changetype<OrchestratorAction | null>(
      store.get("OrchestratorAction", id)
    );
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value!.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get from(): string {
    let value = this.get("from");
    return value!.toString();
  }

  set from(value: string) {
    this.set("from", Value.fromString(value));
  }

  get votes(): Array<string> {
    let value = this.get("votes");
    return value!.toStringArray();
  }

  set votes(value: Array<string>) {
    this.set("votes", Value.fromStringArray(value));
  }

  get lastUpdated(): BigInt | null {
    let value = this.get("lastUpdated");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set lastUpdated(value: BigInt | null) {
    if (!value) {
      this.unset("lastUpdated");
    } else {
      this.set("lastUpdated", Value.fromBigInt(<BigInt>value));
    }
  }

  get state(): string {
    let value = this.get("state");
    return value!.toString();
  }

  set state(value: string) {
    this.set("state", Value.fromString(value));
  }

  get actionFailed(): Array<string> {
    let value = this.get("actionFailed");
    return value!.toStringArray();
  }

  set actionFailed(value: Array<string>) {
    this.set("actionFailed", Value.fromStringArray(value));
  }

  get status(): string {
    let value = this.get("status");
    return value!.toString();
  }

  set status(value: string) {
    this.set("status", Value.fromString(value));
  }

  set recipients(value: Array<string>) {
    this.set("recipients", Value.fromStringArray(value));
  }

  get recipients(): Array<string> {
    let value = this.get("recipients");
    return value!.toStringArray();
  }

  set hash(value: string) {
    this.set("hash", Value.fromString(value));
  }

  get hash(): string {
    let value = this.get("hash");
    return value!.toString();
  }

  set gasUsed(value: BigInt) {
    this.set("gasUsed", Value.fromBigInt(value));
  }

  get gasUsed(): BigInt {
    let value = this.get("gasUsed");
    return value!.toBigInt();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value!.toString();
  }

  set vault(value: string) {
    this.set("vault", Value.fromString(value));
  }

  get vault(): string {
    let value = this.get("vault");
    return value!.toString();
  }
  
}

export class Vote extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("timestamp", Value.fromBigInt(BigInt.zero()));
    this.set("by", Value.fromString(""));
    this.set("action", Value.fromString(""));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Vote entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Vote entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Vote", id.toString(), this);
    }
  }

  static load(id: string): Vote | null {
    return changetype<Vote | null>(store.get("Vote", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value!.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get by(): string {
    let value = this.get("by");
    return value!.toString();
  }

  set by(value: string) {
    this.set("by", Value.fromString(value));
  }

  get action(): string {
    let value = this.get("action");
    return value!.toString();
  }

  set action(value: string) {
    this.set("action", Value.fromString(value));
  }
}

export class VaultPosition extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("upperTick", Value.fromBigIntArray(new Array(0)));
    this.set("lowerTick", Value.fromBigIntArray(new Array(0)));
    this.set("vault", Value.fromString(""));
    this.set("relativeWeight", Value.fromBigIntArray(new Array(0)));
    this.set("timestamp", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save VaultPosition entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        `Entities of type VaultPosition must have an ID of type String but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("VaultPosition", id.toString(), this);
    }
  }

  static load(id: string): VaultPosition | null {
    return changetype<VaultPosition | null>(store.get("VaultPosition", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get upperTick(): Array<BigInt> {
    let value = this.get("upperTick");
    return value!.toBigIntArray();
  }

  set upperTick(value: Array<BigInt>) {
    this.set("upperTick", Value.fromBigIntArray(value));
  }

  get lowerTick(): Array<BigInt> {
    let value = this.get("lowerTick");
    return value!.toBigIntArray();
  }

  set lowerTick(value: Array<BigInt>) {
    this.set("lowerTick", Value.fromBigIntArray(value));
  }

  get vault(): string {
    let value = this.get("vault");
    return value!.toString();
  }

  set vault(value: string) {
    this.set("vault", Value.fromString(value));
  }

  get relativeWeight(): Array<BigInt> {
    let value = this.get("relativeWeight");
    return value!.toBigIntArray();
  }

  set relativeWeight(value: Array<BigInt>) {
    this.set("relativeWeight", Value.fromBigIntArray(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value!.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }
}

export class ActionFailure extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
    this.set("method", Value.fromBigInt(BigInt.zero()));
    this.set("action", Value.fromString(""));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save ActionFailure entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save ActionFailure entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("ActionFailure", id.toString(), this);
    }
  }

  static load(id: string): ActionFailure | null {
    return changetype<ActionFailure | null>(store.get("ActionFailure", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }

  get method(): BigInt {
    let value = this.get("method");
    return value!.toBigInt();
  }

  set method(value: BigInt) {
    this.set("method", Value.fromBigInt(value));
  }

  get action(): string {
    let value = this.get("action");
    return value!.toString();
  }

  set action(value: string) {
    this.set("action", Value.fromString(value));
  }
}

export class Creator extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("revenue", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("totalValueLocked", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("totalYield", Value.fromBigDecimal(BigDecimal.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Creator entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Creator entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Creator", id.toString(), this);
    }
  }

  static load(id: string): Creator | null {
    return changetype<Creator | null>(store.get("Creator", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get strategies(): Array<string> {
    let value = this.get("strategies");
    return value!.toStringArray();
  }

  set strategies(value: Array<string>) {
    this.set("strategies", Value.fromStringArray(value));
  }

  get revenue(): BigDecimal {
    let value = this.get("revenue");
    return value!.toBigDecimal();
  }

  set revenue(value: BigDecimal) {
    this.set("revenue", Value.fromBigDecimal(value));
  }

  get withdrawals(): Array<string> | null {
    let value = this.get("withdrawals");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set withdrawals(value: Array<string> | null) {
    if (!value) {
      this.unset("withdrawals");
    } else {
      this.set("withdrawals", Value.fromStringArray(<Array<string>>value));
    }
  }

  get totalValueLocked(): BigDecimal {
    let value = this.get("totalValueLocked");
    return value!.toBigDecimal();
  }

  set totalValueLocked(value: BigDecimal) {
    this.set("totalValueLocked", Value.fromBigDecimal(value));
  }

  get totalYield(): BigDecimal {
    let value = this.get("totalYield");
    return value!.toBigDecimal();
  }

  set totalYield(value: BigDecimal) {
    this.set("totalYield", Value.fromBigDecimal(value));
  }
}

export class CreatorWithdrawal extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
    this.set("creator", Value.fromString(""));
    this.set("amount", Value.fromBigDecimal(BigDecimal.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save CreatorWithdrawal entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save CreatorWithdrawal entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("CreatorWithdrawal", id.toString(), this);
    }
  }

  static load(id: string): CreatorWithdrawal | null {
    return changetype<CreatorWithdrawal | null>(
      store.get("CreatorWithdrawal", id)
    );
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }

  get creator(): string {
    let value = this.get("creator");
    return value!.toString();
  }

  set creator(value: string) {
    this.set("creator", Value.fromString(value));
  }

  get amount(): BigDecimal {
    let value = this.get("amount");
    return value!.toBigDecimal();
  }

  set amount(value: BigDecimal) {
    this.set("amount", Value.fromBigDecimal(value));
  }
}

export class Strategy extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("name", Value.fromString(""));
    this.set("createdAt", Value.fromBigInt(BigInt.zero()));
    this.set("admin", Value.fromString(""));
    this.set("creator", Value.fromString(""));
    this.set("executionBundle", Value.fromString(""));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Strategy entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Strategy entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Strategy", id.toString(), this);
    }
  }

  static load(id: string): Strategy | null {
    return changetype<Strategy | null>(store.get("Strategy", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value!.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get vault(): Array<string> {
    let value = this.get("vault");
    return value!.toStringArray();
  }

  set vault(value: Array<string>) {
    this.set("vault", Value.fromStringArray(value));
  }

  get createdAt(): BigInt {
    let value = this.get("createdAt");
    return value!.toBigInt();
  }

  set createdAt(value: BigInt) {
    this.set("createdAt", Value.fromBigInt(value));
  }

  get admin(): string {
    let value = this.get("admin");
    return value!.toString();
  }

  set admin(value: string) {
    this.set("admin", Value.fromString(value));
  }

  get creator(): string {
    let value = this.get("creator");
    return value!.toString();
  }

  set creator(value: string) {
    this.set("creator", Value.fromString(value));
  }

  get executionBundle(): string {
    let value = this.get("executionBundle");
    return value!.toString();
  }

  set executionBundle(value: string) {
    this.set("executionBundle", Value.fromString(value));
  }
}

export class Vault extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
    this.set("deployer", Value.fromString(""));
    this.set("token0", Value.fromString(""));
    this.set("token1", Value.fromString(""));
    this.set("beaconName", Value.fromString(""));
    this.set("totalAmount0", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("totalAmount1", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("createdAt", Value.fromBigInt(BigInt.zero()));
    this.set("lastSnapshot", Value.fromBigInt(BigInt.zero()));
    this.set("state", Value.fromBigInt(BigInt.zero()));
    this.set("strategyToken", Value.fromString(""));
    this.set("annualPercentageYield", Value.fromBigDecimal(BigDecimal.zero()));
    this.set(
      "annualPercentageDailyYield",
      Value.fromBigDecimal(BigDecimal.zero())
    );
    this.set(
      "annualPercentageMonthlyYield",
      Value.fromBigDecimal(BigDecimal.zero())
    );
    this.set(
      "annualPercentageYearlyYield",
      Value.fromBigDecimal(BigDecimal.zero())
    );

    this.set("pool", Value.fromString(""));
    this.set("lastTotalT0ValuePerLPT", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("accruedStrategistFees0", Value.fromBigInt(BigInt.zero()));
    this.set("accruedStrategistFees1", Value.fromBigInt(BigInt.zero()));
    this.set("fees0", Value.fromBigInt(BigInt.zero()));
    this.set("fees1", Value.fromBigInt(BigInt.zero()));
    this.set("gasUsed", Value.fromBigInt(BigInt.zero()));
    this.set("gasDeposited", Value.fromBigInt(BigInt.zero()));
    this.set("totalLPTokensIssued", Value.fromBigInt(BigInt.zero()));
    this.set("token1Symbol", Value.fromString(""));
    this.set("decimals", Value.fromBigInt(BigInt.zero()));
    this.set("feeTier", Value.fromBigInt(BigInt.zero()));
    this.set("name", Value.fromString(""));
    this.set("symbol", Value.fromString(""));
    this.set("token0Balance", Value.fromBigInt(BigInt.zero()));
    this.set("token0Decimals", Value.fromBigInt(BigInt.zero()));
    this.set("token0Name", Value.fromString(""));
    this.set("token0Symbol", Value.fromString(""));
    this.set("token1Balance", Value.fromBigInt(BigInt.zero()));
    this.set("token1Decimals", Value.fromBigInt(BigInt.zero()));
    this.set("token1Name", Value.fromString(""));
    this.set("payloadIpfs", Value.fromString(""));
    this.set('vaultManager', Value.fromString(""));
    this.set('averageFeeArrPerSecond', Value.fromBigDecimal(BigDecimal.zero())); 
    this.set('totalSnapshots', Value.fromBigInt(BigInt.zero()));
    this.set('annualFeeARR', Value.fromBigDecimal(BigDecimal.zero()));
    this.set('weeklyFeeAPR', Value.fromBigDecimal(BigDecimal.zero()));
    this.set('dailyFeeAPR', Value.fromBigDecimal(BigDecimal.zero()));
    this.set('totalValueLockedToken0', Value.fromBigDecimal(BigDecimal.zero()));
    this.set('totalValueLockedToken1', Value.fromBigDecimal(BigDecimal.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Vault entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Vault entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Vault", id.toString(), this);
    }
  }

  static load(id: string): Vault | null {
    return changetype<Vault | null>(store.get("Vault", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get deployer(): string {
    let value = this.get("deployer");
    return value!.toString();
  }

  set deployer(value: string) {
    this.set("deployer", Value.fromString(value));
  }

  get pool(): string {
    let value = this.get("pool");
    return value!.toString();
  }

  set pool(value: string) {
    this.set("pool", Value.fromString(value));
  }

  get beaconName(): string {
    let value = this.get("beaconName");
    return value!.toString();
  }

  set beaconName(value: string) {
    this.set("beaconName", Value.fromString(value));
  }

  get token0(): string {
    let value = this.get("token0");
    return value!.toString();
  }

  set token0(value: string) {
    this.set("token0", Value.fromString(value));
  }

  get token1(): string {
    let value = this.get("token1");
    return value!.toString();
  }

  set token1(value: string) {
    this.set("token1", Value.fromString(value));
  }

  get totalAmount0(): BigDecimal {
    let value = this.get("totalAmount0");
    return value!.toBigDecimal();
  }

  set totalAmount0(value: BigDecimal) {
    this.set("totalAmount0", Value.fromBigDecimal(value));
  }

  get totalValueLockedToken0(): BigDecimal {
    let value = this.get("totalValueLockedToken0");
    return value!.toBigDecimal();
  }

  set totalValueLockedToken0(value: BigDecimal) {
    this.set("totalValueLockedToken0", Value.fromBigDecimal(value));
  }

  get totalValueLockedToken1(): BigDecimal {
    let value = this.get("totalValueLockedToken1");
    return value!.toBigDecimal();
  }

  set totalValueLockedToken1(value: BigDecimal) {
    this.set("totalValueLockedToken1", Value.fromBigDecimal(value));
  }

  get totalAmount1(): BigDecimal {
    let value = this.get("totalAmount1");
    return value!.toBigDecimal();
  }

  set totalAmount1(value: BigDecimal) {
    this.set("totalAmount1", Value.fromBigDecimal(value));
  }

  get createdAt(): BigInt {
    let value = this.get("createdAt");
    return value!.toBigInt();
  }

  set createdAt(value: BigInt) {
    this.set("createdAt", Value.fromBigInt(value));
  }

  get lastSnapshot(): BigInt {
    let value = this.get("lastSnapshot");
    return value!.toBigInt();
  }

  set lastSnapshot(value: BigInt) {
    this.set("lastSnapshot", Value.fromBigInt(value));
  }

  get state(): BigInt {
    let value = this.get("state");
    return value!.toBigInt();
  }

  set state(value: BigInt) {
    this.set("state", Value.fromBigInt(value));
  }

  get statusUpdates(): Array<string> {
    let value = this.get("statusUpdates");
    return value!.toStringArray();
  }

  set statusUpdates(value: Array<string>) {
    this.set("statusUpdates", Value.fromStringArray(value));
  }

  get strategyToken(): string {
    let value = this.get("strategyToken");
    return value!.toString();
  }

  set strategyToken(value: string) {
    this.set("strategyToken", Value.fromString(value));
  }

  get snapshots(): Array<string> {
    let value = this.get("snapshots");
    return value!.toStringArray();
  }

  set snapshots(value: Array<string>) {
    this.set("snapshots", Value.fromStringArray(value));
  }

  get annualPercentageYield(): BigDecimal {
    let value = this.get("annualPercentageYield");
    return value!.toBigDecimal();
  }

  set annualPercentageYield(value: BigDecimal) {
    this.set("annualPercentageYield", Value.fromBigDecimal(value));
  }

  get annualPercentageDailyYield(): BigDecimal {
    let value = this.get("annualPercentageDailyYield");
    return value!.toBigDecimal();
  }

  set annualPercentageDailyYield(value: BigDecimal) {
    this.set("annualPercentageDailyYield", Value.fromBigDecimal(value));
  }

  get annualPercentageMonthlyYield(): BigDecimal {
    let value = this.get("annualPercentageMonthlyYield");
    return value!.toBigDecimal();
  }

  set annualPercentageMonthlyYield(value: BigDecimal) {
    this.set("annualPercentageMonthlyYield", Value.fromBigDecimal(value));
  }

  get annualPercentageYearlyYield(): BigDecimal {
    let value = this.get("annualPercentageYearlyYield");
    return value!.toBigDecimal();
  }

  set annualPercentageYearlyYield(value: BigDecimal) {
    this.set("annualPercentageYearlyYield", Value.fromBigDecimal(value));
  }

  get lastTotalT0ValuePerLPT(): BigDecimal {
    let value = this.get("lastTotalT0ValuePerLPT");
    return value!.toBigDecimal();
  }

  set lastTotalT0ValuePerLPT(value: BigDecimal) {
    this.set("lastTotalT0ValuePerLPT", Value.fromBigDecimal(value));
  }

  get accruedStrategistFees0(): BigInt {
    let value = this.get("accruedStrategistFees0");
    return value!.toBigInt();
  }

  set accruedStrategistFees0(value: BigInt) {
    this.set("accruedStrategistFees0", Value.fromBigInt(value));
  }

  get accruedStrategistFees1(): BigInt {
    let value = this.get("accruedStrategistFees1");
    return value!.toBigInt();
  }

  set accruedStrategistFees1(value: BigInt) {
    this.set("accruedStrategistFees1", Value.fromBigInt(value));
  }

  get fees0(): BigInt {
    let value = this.get("fees0");
    return value!.toBigInt();
  }

  set fees0(value: BigInt) {
    this.set("fees0", Value.fromBigInt(value));
  }

  get fees1(): BigInt {
    let value = this.get("fees1");
    return value!.toBigInt();
  }

  set fees1(value: BigInt) {
    this.set("fees1", Value.fromBigInt(value));
  }

  get gasUsed(): BigInt {
    let value = this.get("gasUsed");
    return value!.toBigInt();
  }

  set gasUsed(value: BigInt) {
    this.set("gasUsed", Value.fromBigInt(value));
  }

  get gasDeposited(): BigInt {
    let value = this.get("gasDeposited");
    return value!.toBigInt();
  }

  set gasDeposited(value: BigInt) {
    this.set("gasDeposited", Value.fromBigInt(value));
  }

  get totalLPTokensIssued(): BigInt {
    let value = this.get("totalLPTokensIssued");
    return value!.toBigInt();
  }

  set totalLPTokensIssued(value: BigInt) {
    this.set("totalLPTokensIssued", Value.fromBigInt(value));
  }

  get decimals(): BigInt {
    let value = this.get("decimals");
    return value!.toBigInt();
  }

  set decimals(value: BigInt) {
    this.set("decimals", Value.fromBigInt(value));
  }
  get feeTier(): BigInt {
    let value = this.get("feeTier");
    return value!.toBigInt();
  }

  set feeTier(value: BigInt) {
    this.set("feeTier", Value.fromBigInt(value));
  }

  get token0Balance(): BigInt {
    let value = this.get("token0Balance");
    return value!.toBigInt();
  }

  set token0Balance(value: BigInt) {
    this.set("token0Balance", Value.fromBigInt(value));
  }

  get token1Balance(): BigInt {
    let value = this.get("token1Balance");
    return value!.toBigInt();
  }

  set token1Balance(value: BigInt) {
    this.set("token1Balance", Value.fromBigInt(value));
  }

  get token1Decimals(): BigInt {
    let value = this.get("token1Decimals");
    return value!.toBigInt();
  }

  set token1Decimals(value: BigInt) {
    this.set("token1Decimals", Value.fromBigInt(value));
  }

  get token0Decimals(): BigInt {
    let value = this.get("token0Decimals");
    return value!.toBigInt();
  }

  set token0Decimals(value: BigInt) {
    this.set("token0Decimals", Value.fromBigInt(value));
  }

  get token1Name(): string {
    let value = this.get("token1Name");
    return value!.toString();
  }

  set token1Name(value: string) {
    this.set("token1Name", Value.fromString(value));
  }

  get payloadIpfs(): string {
    let value = this.get("payloadIpfs");
    return value!.toString();
  }

  set payloadIpfs(value: string) {
    this.set("payloadIpfs", Value.fromString(value));
  }

  get token1Symbol(): string {
    let value = this.get("token1Symbol");
    return value!.toString();
  }

  set token1Symbol(value: string) {
    this.set("token1Symbol", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value!.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get symbol(): string {
    let value = this.get("symbol");
    return value!.toString();
  }

  set symbol(value: string) {
    this.set("symbol", Value.fromString(value));
  }

  get token0Name(): string {
    let value = this.get("token0Name");
    return value!.toString();
  }

  set token0Name(value: string) {
    this.set("token0Name", Value.fromString(value));
  }

  get token0Symbol(): string {
    let value = this.get("token0Symbol");
    return value!.toString();
  }

  set token0Symbol(value: string) {
    this.set("token0Symbol", Value.fromString(value));
  }

  get vaultManager(): string {
    let value = this.get("vaultManager");
    return value!.toString();
  }

  set vaultManager(value: string) {
    this.set("vaultManager", Value.fromString(value));
  }

  get averageFeeArrPerSecond(): BigDecimal {
    let value = this.get("averageFeeArrPerSecond");
    return value!.toBigDecimal();
  }

  set averageFeeArrPerSecond(value: BigDecimal) {
    this.set("averageFeeArrPerSecond", Value.fromBigDecimal(value));
  }

  get totalSnapshots(): BigInt {
    let value = this.get("totalSnapshots");
    return value!.toBigInt();
  }

  set totalSnapshots(value: BigInt) {
    this.set("totalSnapshots", Value.fromBigInt(value));
  }

  get annualFeeARR(): BigDecimal {
    let value = this.get("annualFeeARR");
    return value!.toBigDecimal();
  }

  set annualFeeARR(value: BigDecimal) {
    this.set("annualFeeARR", Value.fromBigDecimal(value));
  }

  get weeklyFeeAPR(): BigDecimal {
    let value = this.get("weeklyFeeAPR");
    return value!.toBigDecimal();
  }

  set weeklyFeeAPR(value: BigDecimal) {
    this.set("weeklyFeeAPR", Value.fromBigDecimal(value));
  }

  get dailyFeeAPR(): BigDecimal {
    let value = this.get("dailyFeeAPR");
    return value!.toBigDecimal();
  }

  set dailyFeeAPR(value: BigDecimal) {
    this.set("dailyFeeAPR", Value.fromBigDecimal(value));
  }
}

export class VaultTransfer extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save VaultTransfer entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        `Entities of type VaultTransfer must have an ID of type String but the id '${id.displayData()}' is of type ${id.displayKind()}`
      );
      store.set("VaultTransfer", id.toString(), this);
    }
  }

  static load(id: string): VaultTransfer | null {
    return changetype<VaultTransfer | null>(store.get("VaultTransfer", id));
  }

  get id(): string {
    let value = this.get("id");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toString();
    }
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get from(): string {
    let value = this.get("from");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toString();
    }
  }

  set from(value: string) {
    this.set("from", Value.fromString(value));
  }

  get to(): string {
    let value = this.get("to");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toString();
    }
  }

  set to(value: string) {
    this.set("to", Value.fromString(value));
  }

  get value(): BigInt {
    let value = this.get("value");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set value(value: BigInt) {
    this.set("value", Value.fromBigInt(value));
  }


  get timestamp(): BigInt {
    let value = this.get("timestamp");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    if (!value || value.kind == ValueKind.NULL) {
      throw new Error("Cannot return null for a required field.");
    } else {
      return value.toBigInt();
    }
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }
}

export class VaultSnapshot extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("vaultAddress", Value.fromString(""));
    this.set("totalAmount0", Value.fromBigInt(BigInt.zero()));
    this.set("totalAmount1", Value.fromBigInt(BigInt.zero()));
    this.set("sqrtPriceX96", Value.fromBigInt(BigInt.zero()));
    this.set("totalSupply", Value.fromBigInt(BigInt.zero()));
    this.set("timestamp", Value.fromBigInt(BigInt.zero()));
    this.set("fees1", Value.fromBigInt(BigInt.zero()));
    this.set("fees0", Value.fromBigInt(BigInt.zero()));
    this.set('annualFeeAPR', Value.fromBigDecimal(BigDecimal.zero()));
    this.set('weeklyFeeAPR', Value.fromBigDecimal(BigDecimal.zero()));
    this.set('dailyFeeAPR', Value.fromBigDecimal(BigDecimal.zero()));
    this.set('transactionHash', Value.fromString(''));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save VaultSnapshot entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save VaultSnapshot entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("VaultSnapshot", id.toString(), this);
    }
  }

  static load(id: string): VaultSnapshot | null {
    return changetype<VaultSnapshot | null>(store.get("VaultSnapshot", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value!.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get vaultAddress(): string {
    let value = this.get("vaultAddress");
    return value!.toString();
  }

  set vaultAddress(value: string) {
    this.set("vaultAddress", Value.fromString(value));
  }

  get totalAmount0(): BigInt {
    let value = this.get("totalAmount0");
    return value!.toBigInt();
  }

  set totalAmount0(value: BigInt) {
    this.set("totalAmount0", Value.fromBigInt(value));
  }

  get totalAmount1(): BigInt {
    let value = this.get("totalAmount1");
    return value!.toBigInt();
  }

  set totalAmount1(value: BigInt) {
    this.set("totalAmount1", Value.fromBigInt(value));
  }

  get sqrtPriceX96(): BigInt {
    let value = this.get("sqrtPriceX96");
    return value!.toBigInt();
  }

  set sqrtPriceX96(value: BigInt) {
    this.set("sqrtPriceX96", Value.fromBigInt(value));
  }

  get totalSupply(): BigInt {
    let value = this.get("totalSupply");
    return value!.toBigInt();
  }

  set totalSupply(value: BigInt) {
    this.set("totalSupply", Value.fromBigInt(value));
  }

  get fees0(): BigInt {
    let value = this.get("fees0");
    return value!.toBigInt();
  }

  set fees0(value: BigInt) {
    this.set("fees0", Value.fromBigInt(value));
  }

  get fees1(): BigInt {
    let value = this.get("fees1");
    return value!.toBigInt();
  }

  set fees1(value: BigInt) {
    this.set("fees1", Value.fromBigInt(value));
  }

  get annualFeeAPR(): BigDecimal {
    let value = this.get("annualFeeAPR");
    return value!.toBigDecimal();
  }

  set annualFeeAPR(value: BigDecimal) {
    this.set("annualFeeAPR", Value.fromBigDecimal(value));
  }

  get weeklyFeeAPR(): BigDecimal {
    let value = this.get("weeklyFeeAPR");
    return value!.toBigDecimal();
  }

  set weeklyFeeAPR(value: BigDecimal) {
    this.set("weeklyFeeAPR", Value.fromBigDecimal(value));
  }

  get dailyFeeAPR(): BigDecimal {
    let value = this.get("dailyFeeAPR");
    return value!.toBigDecimal();
  }

  set dailyFeeAPR(value: BigDecimal) {
    this.set("dailyFeeAPR", Value.fromBigDecimal(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value!.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

}

export class VaultStateChanged extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
    this.set("vault", Value.fromString(""));
    this.set("status", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save VaultStateChanged entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save VaultStateChanged entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("VaultStateChanged", id.toString(), this);
    }
  }

  static load(id: string): VaultStateChanged | null {
    return changetype<VaultStateChanged | null>(
      store.get("VaultStateChanged", id)
    );
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }

  get vault(): string {
    let value = this.get("vault");
    return value!.toString();
  }

  set vault(value: string) {
    this.set("vault", Value.fromString(value));
  }

  get status(): BigInt {
    let value = this.get("status");
    return value!.toBigInt();
  }

  set status(value: BigInt) {
    this.set("status", Value.fromBigInt(value));
  }
}

export class VaultDeposit extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("vault", Value.fromString(""));
    this.set("amount0", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("amount1", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("token0", Value.fromString(""));
    this.set("token1", Value.fromString(""));
    this.set("sender", Value.fromString(""));
    this.set("blockNumber", Value.fromBigInt(BigInt.zero()));
    this.set("executor", Value.fromString(""));
    this.set("depositCaller", Value.fromString(""));
    this.set("transactionHash", Value.fromString(""));
    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
    this.set('shares', Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save VaultDeposit entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save VaultDeposit entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("VaultDeposit", id.toString(), this);
    }
  }

  static load(id: string): VaultDeposit | null {
    return changetype<VaultDeposit | null>(store.get("VaultDeposit", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get vault(): string {
    let value = this.get("vault");
    return value!.toString();
  }

  set vault(value: string) {
    this.set("vault", Value.fromString(value));
  }

  get amount0(): BigDecimal {
    let value = this.get("amount0");
    return value!.toBigDecimal();
  }

  set amount0(value: BigDecimal) {
    this.set("amount0", Value.fromBigDecimal(value));
  }

  get amount1(): BigDecimal {
    let value = this.get("amount1");
    return value!.toBigDecimal();
  }

  set amount1(value: BigDecimal) {
    this.set("amount1", Value.fromBigDecimal(value));
  }

  get token0(): string {
    let value = this.get("token0");
    return value!.toString();
  }

  set token0(value: string) {
    this.set("token0", Value.fromString(value));
  }

  get token1(): string {
    let value = this.get("token1");
    return value!.toString();
  }

  set token1(value: string) {
    this.set("token1", Value.fromString(value));
  }

  get sender(): string {
    let value = this.get("sender");
    return value!.toString();
  }

  set sender(value: string) {
    this.set("sender", Value.fromString(value));
  }

  get executor(): string {
    let value = this.get("executor");
    return value!.toString();
  }

  set executor(value: string) {
    this.set("executor", Value.fromString(value));
  }

  get depositCaller(): string {
    let value = this.get("depositCaller");
    return value!.toString();
  }

  set depositCaller(value: string) {
    this.set("depositCaller", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value!.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }

  get shares(): BigInt {
    let value = this.get("shares");
    return value!.toBigInt();
  }

  set shares(value: BigInt) {
    this.set("shares", Value.fromBigInt(value));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    return value!.toBigInt();
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }
}

export class VaultWithdraw extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("vault", Value.fromString(""));
    this.set("amount0", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("amount1", Value.fromBigDecimal(BigDecimal.zero()));
    this.set("token0", Value.fromString(""));
    this.set("token1", Value.fromString(""));
    this.set("sender", Value.fromString(""));
    this.set("transactionHash", Value.fromString(""))
    this.set("blockNumber", Value.fromBigInt(BigInt.zero()));
    this.set("shares", Value.fromBigInt(BigInt.zero()));
    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save VaultWithdraw entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save VaultWithdraw entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("VaultWithdraw", id.toString(), this);
    }
  }

  static load(id: string): VaultWithdraw | null {
    return changetype<VaultWithdraw | null>(store.get("VaultWithdraw", id));
  }

  get blockNumber(): BigInt {
    let value = this.get("blockNumber");
    return value!.toBigInt();
  }

  set blockNumber(value: BigInt) {
    this.set("blockNumber", Value.fromBigInt(value));
  }

  get shares(): BigInt {
    let value = this.get("shares");
    return value!.toBigInt();
  }

  set shares(value: BigInt) {
    this.set("shares", Value.fromBigInt(value));
  }
  
  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get vault(): string {
    let value = this.get("vault");
    return value!.toString();
  }

  set vault(value: string) {
    this.set("vault", Value.fromString(value));
  }

  get sender(): string {
    let value = this.get("sender");
    return value!.toString();
  }

  set sender(value: string) {
    this.set("sender", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value!.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }


  get amount0(): BigDecimal {
    let value = this.get("amount0");
    return value!.toBigDecimal();
  }

  set amount0(value: BigDecimal) {
    this.set("amount0", Value.fromBigDecimal(value));
  }

  get amount1(): BigDecimal {
    let value = this.get("amount1");
    return value!.toBigDecimal();
  }

  set amount1(value: BigDecimal) {
    this.set("amount1", Value.fromBigDecimal(value));
  }

  get token0(): string {
    let value = this.get("token0");
    return value!.toString();
  }

  set token0(value: string) {
    this.set("token0", Value.fromString(value));
  }

  get token1(): string {
    let value = this.get("token1");
    return value!.toString();
  }

  set token1(value: string) {
    this.set("token1", Value.fromString(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }
}

export class Depositor extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("vault", Value.fromString(""));
    this.set("depositedAmount0", Value.fromBigInt(BigInt.zero()));
    this.set("depositedAmount1", Value.fromBigInt(BigInt.zero()));
    this.set("withdrawnAmount0", Value.fromBigInt(BigInt.zero()));
    this.set("withdrawnAmount1", Value.fromBigInt(BigInt.zero()));
    this.set("shares", Value.fromBigInt(BigInt.zero()));
    this.set("account", Value.fromString(""));
    this.set("executor", Value.fromString(""));
    this.set("depositCaller", Value.fromString(""));
    this.set("liquidityAmount0", Value.fromBigInt(BigInt.zero()));
    this.set("liquidityAmount1", Value.fromBigInt(BigInt.zero()));
    this.set("createdTimestamp", Value.fromBigInt(BigInt.zero()));
    this.set("updatedTimestamp", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Depositor entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Depositor entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Depositor", id.toString(), this);
    }
  }

  static load(id: string): Depositor | null {
    return changetype<Depositor | null>(store.get("Depositor", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get depositedAmount0(): BigInt {
    let value = this.get("depositedAmount0");
    return value!.toBigInt();
  }

  set depositedAmount0(value: BigInt) {
    this.set("depositedAmount0", Value.fromBigInt(value));
  }

  get depositedAmount1(): BigInt {
    let value = this.get("depositedAmount1");
    return value!.toBigInt();
  }

  set depositedAmount1(value: BigInt) {
    this.set("depositedAmount1", Value.fromBigInt(value));
  }

  get withdrawnAmount0(): BigInt {
    let value = this.get("withdrawnAmount0");
    return value!.toBigInt();
  }

  set withdrawnAmount0(value: BigInt) {
    this.set("withdrawnAmount0", Value.fromBigInt(value));
  }

  get withdrawnAmount1(): BigInt {
    let value = this.get("withdrawnAmount1");
    return value!.toBigInt();
  }

  set withdrawnAmount1(value: BigInt) {
    this.set("withdrawnAmount1", Value.fromBigInt(value));
  }

  get shares(): BigInt {
    let value = this.get("shares");
    return value!.toBigInt();
  }

  set shares(value: BigInt) {
    this.set("shares", Value.fromBigInt(value));
  }

  get liquidityAmount0(): BigInt {
    let value = this.get("liquidityAmount0");
    return value!.toBigInt();
  }

  set liquidityAmount0(value: BigInt) {
    this.set("liquidityAmount0", Value.fromBigInt(value));
  }

  get liquidityAmount1(): BigInt {
    let value = this.get("liquidityAmount1");
    return value!.toBigInt();
  }

  set liquidityAmount1(value: BigInt) {
    this.set("liquidityAmount1", Value.fromBigInt(value));
  }


  get createdTimestamp(): BigInt {
    let value = this.get("createdTimestamp");
    return value!.toBigInt();
  }

  set createdTimestamp(value: BigInt) {
    this.set("createdTimestamp", Value.fromBigInt(value));
  }

  get updatedTimestamp(): BigInt {
    let value = this.get("updatedTimestamp");
    return value!.toBigInt();
  }

  set updatedTimestamp(value: BigInt) {
    this.set("updatedTimestamp", Value.fromBigInt(value));
  }

  get vault(): string {
    let value = this.get("vault");
    return value!.toString();
  }

  set vault(value: string) {
    this.set("vault", Value.fromString(value));
  }

  get account(): string {
    let value = this.get("account");
    return value!.toString();
  }

  set account(value: string) {
    this.set("account", Value.fromString(value));
  }

  get executor(): string {
    let value = this.get("executor");
    return value!.toString();
  }

  set executor(value: string) {
    this.set("executor", Value.fromString(value));
  }

  get depositCaller(): string {
    let value = this.get("depositCaller");
    return value!.toString();
  }

  set depositCaller(value: string) {
    this.set("depositCaller", Value.fromString(value));
  }

}

export class LiquiditySteer extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("vault", Value.fromString(""));
    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
    this.set("tick", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save LiquiditySteer entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save LiquiditySteer entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("LiquiditySteer", id.toString(), this);
    }
  }

  static load(id: string): LiquiditySteer | null {
    return changetype<LiquiditySteer | null>(store.get("LiquiditySteer", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get vault(): string {
    let value = this.get("vault");
    return value!.toString();
  }

  set vault(value: string) {
    this.set("vault", Value.fromString(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }

  get tick(): BigInt {
    let value = this.get("tick");
    return value!.toBigInt();
  }

  set tick(value: BigInt) {
    this.set("tick", Value.fromBigInt(value));
  }
}

export class OrchestratorRewardTracker extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
    this.set("rewards", Value.fromStringArray([]));
  }

  static load(id: string): OrchestratorRewardTracker | null {
    return changetype<OrchestratorRewardTracker | null>(
      store.get("OrchestratorRewardTracker", id)
    );
  }

  save(): void {
    let id = this.get("id");
    assert(
      id != null,
      "Cannot save OrchestratorRewardTracker entity without an ID"
    );
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save OrchestratorRewardTracker entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("OrchestratorRewardTracker", id.toString(), this);
    }
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }

  get rewards(): Array<string> {
    let value = this.get("rewards");
    return value!.toStringArray();
  }

  set rewards(value: Array<string>) {
    this.set("rewards", Value.fromStringArray(value));
  }
}

export class OrchestratorReward extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("address", Value.fromString(""));
    this.set("reward", Value.fromBigInt(BigInt.zero()));
    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
    this.set("updatedTimeStamp", Value.fromBigInt(BigInt.zero()));
    this.set("trackerId", Value.fromString(""));
  }

  static load(id: string): OrchestratorReward | null {
    return changetype<OrchestratorReward | null>(
      store.get("OrchestratorReward", id)
    );
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save OrchestratorReward entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save OrchestratorReward entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("OrchestratorReward", id.toString(), this);
    }
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get address(): string {
    let value = this.get("address");
    return value!.toString();
  }

  set address(value: string) {
    this.set("address", Value.fromString(value));
  }

  get reward(): BigInt {
    let value = this.get("reward");
    return value!.toBigInt();
  }

  set reward(value: BigInt) {
    this.set("reward", Value.fromBigInt(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }

  get updatedTimeStamp(): BigInt {
    let value = this.get("updatedTimeStamp");
    return value!.toBigInt();
  }

  set updatedTimeStamp(value: BigInt) {
    this.set("updatedTimeStamp", Value.fromBigInt(value));
  }

  get trackerId(): string {
    let value = this.get("trackerId");
    return value!.toString();
  }

  set trackerId(value: string) {
    this.set("trackerId", Value.fromString(value));
  }
}

export class OrchestratorRewardSnapshot extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("address", Value.fromString(""));
    this.set("reward", Value.fromBigInt(BigInt.zero()));
    this.set("timeStamp", Value.fromBigInt(BigInt.zero()));
    this.set("updatedTimeStamp", Value.fromBigInt(BigInt.zero()));
  }

  static load(id: string): OrchestratorRewardSnapshot | null {
    return changetype<OrchestratorRewardSnapshot | null>(
      store.get("OrchestratorRewardSnapshot", id)
    );
  }

  save(): void {
    let id = this.get("id");
    assert(
      id != null,
      "Cannot save OrchestratorRewardSnapshot entity without an ID"
    );
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save OrchestratorRewardSnapshot entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("OrchestratorRewardSnapshot", id.toString(), this);
    }
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get address(): string {
    let value = this.get("address");
    return value!.toString();
  }

  set address(value: string) {
    this.set("address", Value.fromString(value));
  }

  get reward(): BigInt {
    let value = this.get("reward");
    return value!.toBigInt();
  }

  set reward(value: BigInt) {
    this.set("reward", Value.fromBigInt(value));
  }

  get timeStamp(): BigInt {
    let value = this.get("timeStamp");
    return value!.toBigInt();
  }

  set timeStamp(value: BigInt) {
    this.set("timeStamp", Value.fromBigInt(value));
  }

  get updatedTimeStamp(): BigInt {
    let value = this.get("updatedTimeStamp");
    return value!.toBigInt();
  }

  set updatedTimeStamp(value: BigInt) {
    this.set("updatedTimeStamp", Value.fromBigInt(value));
  }
}

export class Bundle extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
    this.set("hash", Value.fromString(""));
    this.set("createdAt", Value.fromBigInt(BigInt.zero()));
    this.set("bundle", Value.fromString(""));
    this.set("creator", Value.fromString(""));
    this.set("host", Value.fromString(""));
    this.set("source", Value.fromString(""));
    this.set("output", Value.fromString(""));
    this.set("infoHash", Value.fromString(""));
    this.set("active", Value.fromBoolean(false));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Bundle entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Bundle entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Bundle", id.toString(), this);
    }
  }

  static load(id: string): Bundle | null {
    return changetype<Bundle | null>(store.get("Bundle", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get createdAt(): BigInt {
    let value = this.get("createdAt");
    return value!.toBigInt();
  }

  set createdAt(value: BigInt) {
    this.set("createdAt", Value.fromBigInt(value));
  }

  get hash(): string {
    let value = this.get("hash");
    return value!.toString();
  }

  set hash(value: string) {
    this.set("hash", Value.fromString(value));
  }

  get infoHash(): string {
    let value = this.get("infoHash");
    return value!.toString();
  }

  set infoHash(value: string) {
    this.set("infoHash", Value.fromString(value));
  }

  get bundle(): string {
    let value = this.get("bundle");
    return value!.toString();
  }

  set bundle(value: string) {
    this.set("bundle", Value.fromString(value));
  }

  get host(): string {
    let value = this.get("host");
    return value!.toString();
  }

  set host(value: string) {
    this.set("host", Value.fromString(value));
  }

  get creator(): string {
    let value = this.get("creator");
    return value!.toString();
  }

  set creator(value: string) {
    this.set("creator", Value.fromString(value));
  }

  get source(): string {
    let value = this.get("source");
    return value!.toString();
  }

  set source(value: string) {
    this.set("source", Value.fromString(value));
  }

  get output(): string {
    let value = this.get("output");
    return value!.toString();
  }

  set output(value: string) {
    this.set("output", Value.fromString(value));
  }

  get active(): boolean {
    let value = this.get("active");
    return value!.toBoolean();
  }

  set active(value: boolean) {
    this.set("active", Value.fromBoolean(value));
  }
}

export class VaultBeacon extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("address", Value.fromString(""));
    this.set("ipfsHash", Value.fromString(""));
    this.set("name", Value.fromString(""));
    this.set("status", Value.fromString(""));
    this.set("timestamp", Value.fromBigInt(BigInt.zero()));
    this.set("updateTimestamp", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save VaultBeacon entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save VaultBeacon entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("VaultBeacon", id.toString(), this);
    }
  }

  static load(id: string): VaultBeacon | null {
    return changetype<VaultBeacon | null>(store.get("VaultBeacon", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get address(): string {
    let value = this.get("address");
    return value!.toString();
  }

  set address(value: string) {
    this.set("address", Value.fromString(value));
  }

  get ipfsHash(): string {
    let value = this.get("ipfsHash");
    return value!.toString();
  }

  set ipfsHash(value: string) {
    this.set("ipfsHash", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value!.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get status(): string {
    let value = this.get("status");
    return value!.toString();
  }

  set status(value: string) {
    this.set("status", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value!.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get updateTimestamp(): BigInt {
    let value = this.get("updateTimestamp");
    return value!.toBigInt();
  }

  set updateTimestamp(value: BigInt) {
    this.set("updateTimestamp", Value.fromBigInt(value));
  }
}
