import { Address } from "@graphprotocol/graph-ts";

export const STRATEGY_FACTORY_ADDRESS = Address.fromString(
  "0x490ff427bBfd662D97CA0533B88f663e6EfED4Cf"
);

export const STEER_PERIPHERY_ADDRESS_MUMBAI = Address.fromString(
  "0x5248661e4fd7c59C87222806506E905752978800"
);

export const STEER_PERIPHERY_ADDRESS_GOERLI = Address.fromString(
  "0x4023AB29dd224Bf5eD71fe5e2Be92637d0176c4C"
);

export const STEER_PERIPHERY_ADDRESS_MATIC = Address.fromString(
  "0x29E1888F7DD0757f2873E494463Ec389dab38D27"
);

export const STEER_PERIPHERY_ADDRESS_ARBITRUM_GOERLI = Address.fromString(
  "0x5248661e4fd7c59C87222806506E905752978800"
);

export const STEER_PERIPHERY_ADDRESS_ARBITRUM = Address.fromString(
  "0x806c2240793b3738000fcb62C66BF462764B903F"
);

export const STEER_PERIPHERY_ADDRESS_OPTIMISM_GOERLI = Address.fromString(
  "0x5248661e4fd7c59C87222806506E905752978800"
);

export const STEER_PERIPHERY_ADDRESS_OPTIMISM = Address.fromString(
  "0x7c464A0AB1f5ebf3E2dCccfec7EF41D02ED7a2f4"
);

export const STEER_PERIPHERY_ADDRESS_BSC = Address.fromString(
  "0xe240B9a2936f6Fb8860219bC059349e50F03492e"
);

export const STEER_PERIPHERY_AVALANCHE = Address.fromString(
  "0x5D8249e3F5f702e1Fd720167b40424fc2daDCd1e"
);

export const STEER_PERIPHERY_ADDRESS_EVMOS = Address.fromString(
  '0x1afD31627170607657224eD4aE701470209C4B2e'
)

export const STEER_PERIPHERY_ADDRESS_METIS = Address.fromString(
  '0x806c2240793b3738000fcb62C66BF462764B903F'
)

export const STEER_PERIPHERY_ADDRESS_ZKEVM = Address.fromString(
  '0xcA19bEc25A41443F35EeAE03411Dce87D8c0Edc4'
)

export const STEER_PERIPHERY_ADDRESS_CELO = Address.fromString(
  '0xdca3251Ebe8f85458E8d95813bCb816460e4bef1'
)

export const STEER_PERIPHERY_ADDRESS_THUNDERCORE = Address.fromString(
  "0xab36D30C1A1C683037Bd7AAC67f29B2e3ECC6576"
)

export const STEER_PERIPHERY_ADDRESS_BASE = Address.fromString(
  '0x16BA7102271dC83Fff2f709691c2B601DAD7668e'
)

export const STEER_PERIPHERY_ADDRESS_LINEA = Address.fromString(
  '0x0C5c5BEB833fD382b04e039f151942DC3D9A60ce'
)

export const STEER_PERIPHERY_ADDRESS_SCROLL = Address.fromString(
  '0xD90c8970708FfdFC403bdb56636621e3E9CCe921'
)

export const STEER_PERIPHERY_ADDRESS_MANTA = Address.fromString(
  '0xD90c8970708FfdFC403bdb56636621e3E9CCe921'
)

export const STEER_PERIPHERY_ADDRESS_KAVA = Address.fromString(
  '0xf90107890B640387ec3b0474F0c61674AEbCb510'
)

export const STEER_PERIPHERY_ADDRESS_ASTAR = Address.fromString(
  '0x1afD31627170607657224eD4aE701470209C4B2e'
)

export const STEER_PERIPHERY_ADDRESS_MANTLE = Address.fromString(
  '0x93df721C732a46227aE1c0710CE0E5A5a6c41eb5'
)

export const STEER_PERIPHERY_ADDRESS_FANTOM = Address.fromString(
  '0xcb77e4C30D92c8b959811E99213625C7b9490b96'
)

export const STEER_PERIPHERY_ADDRESS_OKXTESTNET= Address.fromString(
  '0x22Ee5c43031F045f792cCd81c8fEcf70e51B1011'
)

export const STEER_PERIPHERY_ADDRESS_BLAST= Address.fromString(
  '0xdca3251Ebe8f85458E8d95813bCb816460e4bef1'
)

export const STEER_PERIPHERY_ADDRESS_ASTARKZEVM= Address.fromString(
  '0x37Cff062D52Dd6E9E39Df619CCd30c037a36bB83'
)

export const STEER_PERIPHERY_ADDRESS_MODE = Address.fromString(
  '0x16BA7102271dC83Fff2f709691c2B601DAD7668e'
)


export const STEER_PERIPHERY_ADDRESS_TELOS = Address.fromString(
  '0x16BA7102271dC83Fff2f709691c2B601DAD7668e'
)


export const STEER_PERIPHERY_ADDRESS_XLAYER = Address.fromString(
  '0xab36D30C1A1C683037Bd7AAC67f29B2e3ECC6576'
)

export const STEER_PERIPHERY_ADDRESS_TAIKO = Address.fromString(
  "0xD40699A642172DeD33BCFe4E3F84D54610C757Cd"
)

export const STEER_PERIPHERY_ADDRESS_FLARE = Address.fromString(
  "0x7Daa68204232a78dBF1Dd853a4018330EE934A39"
)

export const STEER_PERIPHERY_ADDRESS_ROOTSTOCK = Address.fromString(
  "0x37Cff062D52Dd6E9E39Df619CCd30c037a36bB83"
)

export const STEER_PERIPHERY_ADDRESS_ZKLINKNOVA = Address.fromString(
  "0x525b443C8d2D0aA8Bd70d22177EC6250286b9708")

export const STEER_PERIPHERY_ADDRESS_BERACHAIN_BARITO = Address.fromString(
  "0xb503E92D4e60b3E4F3c4D1F5037BaBde07994D4C"
)

export const STEER_PERIPHERY_ADDRESS_FILECOIN = Address.fromString(
  "0xab36D30C1A1C683037Bd7AAC67f29B2e3ECC6576"
)

export const BEACON_NAME_MULTI_POSITION_UNISWAP = "MultiPositionUniswapV3";
export const BEACON_NAME_MULTI_POSITION_UNISWAP_SUSHI = "MultiPositionSushi";
export const BEACON_NAME_MULTI_POSITION_UNISWAP_FORGE = "MultiPositionForge";
export const BEACON_NAME_MULTI_POSITION_UNISWAP_MAIA = "MultiPositionMAIA";
export const BEACON_NAME_MULTI_POSITION_UNISWAP_PANCAKE = "MultiPositionPancake";
export const BEACON_NAME_MULTI_POSITION_UNISWAP_METAVAULT = "MultiPositionMetaVault";
export const BEACON_NAME_MULTI_POSITION_UNISWAP_QUICKSWAP = "MultiPositionQuickSwap";
export const BEACON_NAME_MULTI_POSITION_QUICKSWAP = "MultiPositionQuickSwap";
export const BEACON_NAME_MULTI_POSITION_QUICKSWAP_CAMLOT = "MultiPositionCamlot";
export const BEACON_NAME_MULTI_POSITION_ARTHSWAP = "MultiPositionArthSwap";
export const BEACON_NAME_MULTI_POSITION_HERCULES = "MultiPositionHercules";
export const BEACON_NAME_MULTI_POSITION_THRUSTER = "MultiPositionThruster";
export const BEACON_NAME_MULTI_POSITION_QUICKSWAP19 = "MultiPositionQuickSwap19";
export const BEACON_NAME_MULTI_POSITION_HENJIN = "MultiPositionHenjin";



export const BEACON_NAME_SINGLE_POSITION_UNISWAP = "SinglePositionUniswapV3";
export const BEACON_NAME_SINGLE_POSITION_UNISWAP_SUSHI = "SinglePositionSushi";
export const BEACON_NAME_SINGLE_POSITION_UNISWAP_FORGE = "SinglePositionForge";
export const BEACON_NAME_SINGLE_POSITION_UNISWAP_MAIA = "SinglePositionMAIA";
export const BEACON_NAME_SINGLE_POSITION_UNISWAP_PANCAKE = "SinglePositionPancake";
export const BEACON_NAME_SINGLE_POSITION_UNISWAP_METAVAULT = "SinglePositionMetaVault";
export const BEACON_NAME_SINGLE_POSITION_UNISWAP_QUICKSWAP = "SinglePositionQuickSwap";
export const BEACON_NAME_SINGLE_POSITION_ARTHSWAP = "SinglePositionArthSwap";
export const BEACON_NAME_SINGLE_POSITION_THRUSTER = "SinglePositionThruster";
export const BEACON_NAME_SINGLE_POSITION_QUICKSWAP19 = "SinglePositionQuickSwap19";
export const BEACON_NAME_SINGLE_POSITION_HENJIN = "SinglePositionHenjin";


export const BEACON_NAME_SINGLE_POSITION_QUICKSWAP = "SinglePositionQuickSwap";
export const BEACON_NAME_SINGLE_POSITION_QUICKSWAP_CAMLOT = "SinglePositionCamelot";
export const BEACON_NAME_SINGLE_POSITION_HERCULES = "SinglePositionHercules";



export const BEACON_NAME_SINGLE_SCHEDULED_JOBS = "ScheduledJobs";
export const BEACON_NAME_DYNAMIC_JOBS = "DynamicJobs";

export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3 =
  "PermissionedMultiPositionUniswapV3";
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_SUSHI =
  "PermissionedMultiPositionSushi";
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_FORGE =
  "PermissionedMultiPositionForge";
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_MAIA =
  "PermissionedMultiPositionMAIA"
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_PANCAKE =
  "PermissionedMultiPositionPancake"
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_METAVAULT =
  "PermissionedMultiPositionMetaVault"
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_QUICKSWAP = 
 "PermissionedSinglePositionQuickswapUniV3"
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_QUICKSWAP_CAMLOT =
  "PermissionedMultiPositionCamlot"
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_QUICKSWAP =
  "PermissionedMultiPositionQuickSwap"
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_ARTHSWAP =
  "PermissionedMultiPositionArthSwap"
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_HERCULES =
  "PermissionedMultiPositionHercules"
export const BEACON_NAME_PERMISSIONED_MULTI_POSITION_THRUSTER =
  "PermissionedMultiPositionThruster"


export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_SUSHI =
  "PermissionedSinglePositionSushi";
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3 =
  "PermissionedSinglePositionUniswapV3";
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_FORGE =
  "PermissionedMultiPositionForge";
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_MAIA = 
  "PermissionedSinglePositionMAIA"
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_PANCAKE =
  "PermissionedSinglePositionPancake"
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_METAVAULT =
  "PermissionedSinglePositionMetaVault"
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_QUICKSWAP =
  "PermissionedSinglePositionQuickSwap"

export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_QUICKSWAP_CAMELOT =
  "PermissionedSinglePositionCamelot"
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_QUICKSWAP =
  "PermissionedSinglePositionQuickSwap"
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_ARTHSWAP =
  "PermissionedSinglePositionArthSwap"
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_HERCULES =
 "PermissionedSinglePositionHercules"
export const BEACON_NAME_PERMISSIONED_SINGLE_POSITION_THRUSTER =
 "PermissionedSinglePositionThruster"



export const BEACONS_MULTI_POSITIONS = [
  BEACON_NAME_MULTI_POSITION_UNISWAP,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_SUSHI,
  BEACON_NAME_MULTI_POSITION_UNISWAP_SUSHI,
  BEACON_NAME_MULTI_POSITION_UNISWAP_FORGE,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_FORGE,
  BEACON_NAME_MULTI_POSITION_UNISWAP_MAIA,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_MAIA,
  BEACON_NAME_MULTI_POSITION_UNISWAP_PANCAKE,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_PANCAKE,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_METAVAULT,
  BEACON_NAME_MULTI_POSITION_UNISWAP_METAVAULT,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_QUICKSWAP,
  BEACON_NAME_MULTI_POSITION_UNISWAP_QUICKSWAP,

  BEACON_NAME_PERMISSIONED_MULTI_POSITION_QUICKSWAP,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_QUICKSWAP_CAMLOT,

  BEACON_NAME_PERMISSIONED_MULTI_POSITION_ARTHSWAP,
  BEACON_NAME_MULTI_POSITION_ARTHSWAP,

  BEACON_NAME_MULTI_POSITION_HERCULES,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_HERCULES,

  BEACON_NAME_MULTI_POSITION_THRUSTER,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_THRUSTER,

  BEACON_NAME_MULTI_POSITION_HENJIN

];

export const BEACONS_SINGLE_POSITIONS = [
  BEACON_NAME_SINGLE_POSITION_UNISWAP,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_SUSHI,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_SUSHI,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_FORGE,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_FORGE,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_MAIA,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_MAIA,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_PANCAKE,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_PANCAKE,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_METAVAULT,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_METAVAULT,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_QUICKSWAP,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_QUICKSWAP,
  
  BEACON_NAME_SINGLE_POSITION_QUICKSWAP,
  BEACON_NAME_SINGLE_POSITION_QUICKSWAP_CAMLOT,

  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_ARTHSWAP,
  BEACON_NAME_SINGLE_POSITION_ARTHSWAP,

  BEACON_NAME_SINGLE_POSITION_HERCULES,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_HERCULES,

  BEACON_NAME_SINGLE_POSITION_THRUSTER,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_THRUSTER,
  BEACON_NAME_SINGLE_POSITION_QUICKSWAP19,

  BEACON_NAME_SINGLE_POSITION_HENJIN
];

export const BEACONS_UNISWAP = [
  BEACON_NAME_MULTI_POSITION_UNISWAP,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3,
  BEACON_NAME_SINGLE_POSITION_UNISWAP,
  BEACON_NAME_MULTI_POSITION_UNISWAP_SUSHI,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_SUSHI,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_SUSHI,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_SUSHI,
  BEACON_NAME_MULTI_POSITION_UNISWAP_FORGE,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_FORGE,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_FORGE,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_FORGE,
  BEACON_NAME_MULTI_POSITION_UNISWAP_MAIA,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_MAIA,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_MAIA,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_MAIA,
  BEACON_NAME_MULTI_POSITION_UNISWAP_PANCAKE,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_PANCAKE,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_PANCAKE,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_PANCAKE,
  BEACON_NAME_MULTI_POSITION_UNISWAP_QUICKSWAP,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_QUICKSWAP,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_QUICKSWAP,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_QUICKSWAP,
  BEACON_NAME_MULTI_POSITION_UNISWAP_METAVAULT,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_UNISWAP_V3_METAVAULT,
  BEACON_NAME_SINGLE_POSITION_UNISWAP_METAVAULT,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_UNISWAP_V3_METAVAULT,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_ARTHSWAP,
  BEACON_NAME_SINGLE_POSITION_ARTHSWAP,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_ARTHSWAP,
  BEACON_NAME_MULTI_POSITION_ARTHSWAP,
  BEACON_NAME_PERMISSIONED_SINGLE_POSITION_THRUSTER,
  BEACON_NAME_SINGLE_POSITION_THRUSTER,
  BEACON_NAME_PERMISSIONED_MULTI_POSITION_THRUSTER,
  BEACON_NAME_MULTI_POSITION_THRUSTER,
  BEACON_NAME_MULTI_POSITION_QUICKSWAP
];
