// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class GasDeposited extends ethereum.Event {
  get params(): GasDeposited__Params {
    return new GasDeposited__Params(this);
  }
}

export class GasDeposited__Params {
  _event: GasDeposited;

  constructor(event: GasDeposited) {
    this._event = event;
  }

  get depositor(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get value(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class GasWithdrawn extends ethereum.Event {
  get params(): GasWithdrawn__Params {
    return new GasWithdrawn__Params(this);
  }
}

export class GasWithdrawn__Params {
  _event: GasWithdrawn;

  constructor(event: GasWithdrawn) {
    this._event = event;
  }

  get withdrawer(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get value(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class JobExecuted extends ethereum.Event {
  get params(): JobExecuted__Params {
    return new JobExecuted__Params(this);
  }
}

export class JobExecuted__Params {
  _event: JobExecuted;

  constructor(event: JobExecuted) {
    this._event = event;
  }

  get jobHash(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get executor(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class JobRegistered extends ethereum.Event {
  get params(): JobRegistered__Params {
    return new JobRegistered__Params(this);
  }
}

export class JobRegistered__Params {
  _event: JobRegistered;

  constructor(event: JobRegistered) {
    this._event = event;
  }

  get jobInfo(): Array<Bytes> {
    return this._event.parameters[0].value.toBytesArray();
  }

  get targetAddresses(): Array<Address> {
    return this._event.parameters[1].value.toAddressArray();
  }

  get jobHash(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }

  get name(): string {
    return this._event.parameters[3].value.toString();
  }

  get ipfsForJobDetails(): string {
    return this._event.parameters[4].value.toString();
  }
}

export class JobToggledByCreator extends ethereum.Event {
  get params(): JobToggledByCreator__Params {
    return new JobToggledByCreator__Params(this);
  }
}

export class JobToggledByCreator__Params {
  _event: JobToggledByCreator;

  constructor(event: JobToggledByCreator) {
    this._event = event;
  }

  get jobHash(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get toggle(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class DynamicJobs extends ethereum.SmartContract {
  static bind(address: Address): DynamicJobs {
    return new DynamicJobs("DynamicJobs", address);
  }

  creator(): Address {
    let result = super.call("creator", "creator():(address)", []);

    return result[0].toAddress();
  }

  try_creator(): ethereum.CallResult<Address> {
    let result = super.tryCall("creator", "creator():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  gasBalance(): BigInt {
    let result = super.call("gasBalance", "gasBalance():(uint256)", []);

    return result[0].toBigInt();
  }

  try_gasBalance(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("gasBalance", "gasBalance():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  jobState(param0: Bytes): BigInt {
    let result = super.call("jobState", "jobState(bytes32):(uint256)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);

    return result[0].toBigInt();
  }

  try_jobState(param0: Bytes): ethereum.CallResult<BigInt> {
    let result = super.tryCall("jobState", "jobState(bytes32):(uint256)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  keeperRegistry(): Address {
    let result = super.call("keeperRegistry", "keeperRegistry():(address)", []);

    return result[0].toAddress();
  }

  try_keeperRegistry(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "keeperRegistry",
      "keeperRegistry():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  orchestrator(): Address {
    let result = super.call("orchestrator", "orchestrator():(address)", []);

    return result[0].toAddress();
  }

  try_orchestrator(): ethereum.CallResult<Address> {
    let result = super.tryCall("orchestrator", "orchestrator():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ExecuteJobCall extends ethereum.Call {
  get inputs(): ExecuteJobCall__Inputs {
    return new ExecuteJobCall__Inputs(this);
  }

  get outputs(): ExecuteJobCall__Outputs {
    return new ExecuteJobCall__Outputs(this);
  }
}

export class ExecuteJobCall__Inputs {
  _call: ExecuteJobCall;

  constructor(call: ExecuteJobCall) {
    this._call = call;
  }

  get _targetAddresses(): Array<Address> {
    return this._call.inputValues[0].value.toAddressArray();
  }

  get _userProvidedData(): Array<Bytes> {
    return this._call.inputValues[1].value.toBytesArray();
  }

  get _strategyProvidedData(): Array<Bytes> {
    return this._call.inputValues[2].value.toBytesArray();
  }
}

export class ExecuteJobCall__Outputs {
  _call: ExecuteJobCall;

  constructor(call: ExecuteJobCall) {
    this._call = call;
  }
}

export class InitializeCall extends ethereum.Call {
  get inputs(): InitializeCall__Inputs {
    return new InitializeCall__Inputs(this);
  }

  get outputs(): InitializeCall__Outputs {
    return new InitializeCall__Outputs(this);
  }
}

export class InitializeCall__Inputs {
  _call: InitializeCall;

  constructor(call: InitializeCall) {
    this._call = call;
  }

  get _orchestrator(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _steer(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _internalGovernance(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get _params(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }
}

export class InitializeCall__Outputs {
  _call: InitializeCall;

  constructor(call: InitializeCall) {
    this._call = call;
  }
}

export class RegisterJobCall extends ethereum.Call {
  get inputs(): RegisterJobCall__Inputs {
    return new RegisterJobCall__Inputs(this);
  }

  get outputs(): RegisterJobCall__Outputs {
    return new RegisterJobCall__Outputs(this);
  }
}

export class RegisterJobCall__Inputs {
  _call: RegisterJobCall;

  constructor(call: RegisterJobCall) {
    this._call = call;
  }

  get _userProvidedData(): Array<Bytes> {
    return this._call.inputValues[0].value.toBytesArray();
  }

  get _targetAddresses(): Array<Address> {
    return this._call.inputValues[1].value.toAddressArray();
  }

  get _name(): string {
    return this._call.inputValues[2].value.toString();
  }

  get _ipfsForJobDetails(): string {
    return this._call.inputValues[3].value.toString();
  }
}

export class RegisterJobCall__Outputs {
  _call: RegisterJobCall;

  constructor(call: RegisterJobCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall extends ethereum.Call {
  get inputs(): RenounceOwnershipCall__Inputs {
    return new RenounceOwnershipCall__Inputs(this);
  }

  get outputs(): RenounceOwnershipCall__Outputs {
    return new RenounceOwnershipCall__Outputs(this);
  }
}

export class RenounceOwnershipCall__Inputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall__Outputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class ToggleForCreatorCall extends ethereum.Call {
  get inputs(): ToggleForCreatorCall__Inputs {
    return new ToggleForCreatorCall__Inputs(this);
  }

  get outputs(): ToggleForCreatorCall__Outputs {
    return new ToggleForCreatorCall__Outputs(this);
  }
}

export class ToggleForCreatorCall__Inputs {
  _call: ToggleForCreatorCall;

  constructor(call: ToggleForCreatorCall) {
    this._call = call;
  }

  get _jobHash(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _toggle(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class ToggleForCreatorCall__Outputs {
  _call: ToggleForCreatorCall;

  constructor(call: ToggleForCreatorCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}
